
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "http://boring-hamilton-638bc6/*"
  to = "http://gateway.gladysassistant.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://boring-hamilton-638bc6.netlify.com/*"
  to = "https://gateway.gladysassistant.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://gateway.gladysassistant.com/*"
  to = "https://gateway.gladysassistant.com/:splat"
  status = 302
  force = true


