
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "http://frosty-golick-e2d650.netlify.com/*"
  to = "http://gateway.gladysproject.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://frosty-golick-e2d650.netlify.com/*"
  to = "https://gateway.gladysproject.com/:splat"
  status = 301
  force = true