module.exports = {
  jwtAccessTokenTwoFactorConfigure: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiYmRiMWE5MDItYTY1ZS00NmY5LThjMmEtNWMwOTg0MGUyZTEwIiwic2NvcGUiOlsidHdvLWZhY3Rvci1jb25maWd1cmUiXSwiaWF0IjoxNTM3NDkyMjQwLCJleHAiOjMzMDczNDkyMjQwLCJhdWQiOiJ1c2VyIiwiaXNzIjoiZ2xhZHlzLWdhdGV3YXkifQ.arTWVC6bOQNYc952-_izhD-sDwouVXMJnOnCZYoJ68c'
};